version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=test
    networks:
      - stillwater
networks:
  stillwater:
